#!/bin/bash

set -euo pipefail

RELEASE=""
DEV=""
for i in "$@"; do
    case "${i}" in
        --release)
        RELEASE="${i}"
        shift
        ;;
    esac
done


set -x

cargo build --target aarch64-apple-darwin ${RELEASE}
