version: 2
jobs:
  test:
    docker:
    - image: cimg/rust:1.61.0
    steps:
    - checkout
    - run:
        name: Version information
        command: rustc --version; cargo --version; rustup --version
    - run:
        name: Calculate dependencies
        command: cargo generate-lockfile
    - restore_cache:
        name: Cargo.lock cache
        keys:
        - v2-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
    - run:
        name: install-rust-deps
        command: rustup component add clippy-preview rustfmt-preview
    - run:
        name: test
        command: ./test
    - persist_to_workspace:
        root: .
        paths:
        - target
    - save_cache:
        name: Cargo.lock cache
        key: v2-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
        paths:
        - target
  build:
    docker:
    - image: circleci/rust:1.40.0-stretch
    steps:
    - checkout
    - run:
        name: Version information
        command: rustc --version; cargo --version; rustup --version
    - run:
        name: Calculate dependencies
        command: cargo generate-lockfile
    - restore_cache:
        name: Cargo.lock cache
        keys:
        - v2-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
    - run:
        name: install-apt-deps
        command: sudo apt install -y clang gcc-mingw-w64-x86-64 llvm-4.0-dev musl-tools
    - run:
        name: install-rust-deps
        command: rustup target add x86_64-unknown-linux-musl && rustup target add x86_64-pc-windows-gnu
    - run:
        name: Build all targets
        command: PATH=bin:$PATH ./build --release
    - persist_to_workspace:
        root: .
        paths:
        - target/
    - run:
        name: prep-artifacts
        command: mkdir artifacts && cp target/x86_64-unknown-linux-musl/release/dark-cli artifacts/dark-cli-linux && cp target/x86_64-pc-windows-gnu/release/dark-cli.exe artifacts/dark-cli.exe
    - store_artifacts:
        path:
          artifacts
    - save_cache:
        name: Cargo.lock cache
        paths:
        - target
        key: v2-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
  build-osx:
    macos:
      xcode: "11.0.0"
    steps:
    - checkout
    - run:
        name: Install rustup
        command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - run:
        name: Version information
        command: source ~/.cargo/env; rustc --version; cargo --version; rustup --version
    - run:
        name: Calculate dependencies
        command: source ~/.cargo/env; cargo generate-lockfile
    - restore_cache:
        name: Cargo.lock cache
        keys:
        - v2-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
    - run:
        name: install-rust-deps
        command: source ~/.cargo/env; rustup target add x86_64-apple-darwin
    - run:
        name: Build all targets
        command: source ~/.cargo/env; ln -s $(which clang) ~/.cargo/bin/x86_64-apple-darwin15-clang ; ./build-osx --release
    - persist_to_workspace:
        root: .
        paths:
        - target/
    - run:
        name: prep-artifacts
        command: mkdir artifacts && cp target/x86_64-apple-darwin/release/dark-cli artifacts/dark-cli-apple
    - store_artifacts:
        path:
          artifacts
    - save_cache:
        name: Cargo.lock cache
        paths:
        - target
        key: v2-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - test
    - build
    - build-osx
